language: python
dist: xenial
python:
  - "3.6"
  - "3.7"
env:
  - DJANGO=20
  - DJANGO=21
  - DJANGO=22
  - DJANGO=master

matrix:
  fast_finish: true
  allow_failures:
    - env: DJANGO=master

install: pip install tox-travis codecov
before_script:
  - |
    if [[ -z $TOXENV ]]; then
      export TOXENV=py$(echo $TRAVIS_PYTHON_VERSION | sed -e 's/\.//g')-dj$DJANGO
    fi
  - echo $TOXENV
script: tox
after_success: codecov

jobs:
  include:
    - python: "3.7"
      env: TOXENV=docs
    - stage: deploy
      if: tag IS present
      python: "3.7"
      install: skip
      script: skip
      after_success: true
      deploy:
        provider: pypi
        user: codingjoe
        distributions: sdist bdist_wheel
        on:
          tags: true
        password:
